Repository Itatech-Jr/Modern-School-UI, pull requests merged in 2022-12, with the labels that each got.

#2 Atualizar o readme
  README.md
Labels: documentation

#13 adicionei a tela 016 confiram ai
  Mobile/TelaDoProfessor/ManterAtividades/Tela_016.png
Labels: feature

#11 Adicionei a tela 012 referente a manter frequência dos alunos
  Mobile/TelaDoProfessor/ManterFrequencia/TELA 012.png
Labels: feature

#15 Adicionei a tela 013 deem uma olhada se possivel
  Mobile/TelaDoProfessor/ManterComunicação/tela_013.png
Labels: feature

#18 Adicionando TelaDoProfessor/ManterAtividades/Tela_015
  Mobile/TelaDoProfessor/ManterAtividades/Tela_015.png
Labels: feature

#20 [Add]: tela_020 mobile do administrador
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/tela_020 web do administrador.png
Labels: feature

#19 Revisar o protótipo mobile da Tela_018
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/Tela_018.png
Labels: feature

#16 Criada tela 017, solicito uma observação.
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/Tela_017.png
Labels: feature

#21 [add] Mobile/TelaDoProfessor/ManterAtividades/Tela_014.PNG
  Mobile/TelaDoProfessor/ManterAtividades/Tela_014.png
Labels: feature

#30 tela 017 revisada
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/Tela_017.png
Labels: fix

#45 tela 016 mudanças...
  Mobile/TelaDoProfessor/ManterAtividades/Tela_016.png
Labels: fix

#49 tela 013 a todo vapor
  Mobile/TelaDoProfessor/ManterAtividades/Tela_016.png
  Mobile/TelaDoProfessor/ManterComunicação/tela_013.png
Labels: fix

#48 [HOTFIX]
  Mobile/README.md
  Mobile/TelaDoProfessor/ManterAtividades/Tela_014.png
  Mobile/TelaDoProfessor/ManterAtividades/Tela_015.png
  Mobile/TelaDoProfessor/ManterAtividades/Tela_016.png
  Mobile/TelaDoProfessor/ManterComunicação/tela_013.png
  Mobile/TelaDoProfessor/ManterFrequencia/Tela_012.png
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/Tela_017.png
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/Tela_018.png
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/tela_020.png
Labels: fix

#54 Protótipo mobile da Tela_019.png
  Mobile/TelaManterAlunoEManterTurma/ConsultarAluno/Tela_019.png
Labels: feature

#55 commitzinho da tela 010
  Mobile/TelaDoProfessor/ManterDiarioDeClasse/Tela_010.png
Labels: feature

#56 Adicionada a Tela 023
  Mobile/TelaManterAlunoEManterTurma/ManterTurma/Tela_023.PNG
Labels: feature

#58 Tela 024 adaptada
  Mobile/TelaManterAlunoEManterTurma/ManterTurma/Tela_024.png
Labels: feature
